#!/bin/zsh

#
# Colorful ls using the system /bin/ls.
#
# We use the coloring that /bin/ls can do by itself and add missing colors using sed.
#
# On Mac/BSD, you probably want to set the environment variable LSCOLORS to something like:
#
#   LSCOLORS=exfxcxdxbxegedabagacad
#
# On Linux, you can achieve the same with dircolors(1) and the LS_COLORS variable. A basic
# setup would be:
#
#   eval $(dircolors)
#


# Adjusts to terminal theme by using default colors except the gray gradient.
RED="[0;31m"
RED_BOLD="[1;31m"
GREEN="[0;32m"
GREEN_BOLD="[1;32m"
YELLOW="[0;33m"
YELLOW_BOLD="[1;33m"
CYAN="[0;36m"
CYAN_BOLD="[1;36m"
GRAY0="[38;5;240m"
GRAY1="[38;5;241m"
GRAY4="[38;5;244m"
GRAY8="[38;5;248m"
BLUE="[0;34m"
ITALIC="[3m"
R="[0m"

# Mac/BSD date and ls are a bit different from the GNU/Linux versions
if [[ $OSTYPE == *linux* ]]
then
    LS_OPTS='--color=always -hotrlF --time-style='
    LS_TIMEFMT='+%a %d.%m.%y %H:%M'
    DATE_LAST_YEAR=$(/bin/date '+%y' -d 'last year')
else
    LS_OPTS='--color=always -hotrlD'
    LS_TIMEFMT=' %a %d.%m.%y %H:%M'
    DATE_LAST_YEAR=$(/bin/date -v-1y '+%y')
fi

# Weekday names are locale dependant (2 or 3 characters expected).
# Otherwise the date format is strictly 'Weekday Day.Month.Year Hour:Minute'
# with year in short form ('26', not '2026') and time in 24 hour format. 
/bin/ls ${=LS_OPTS}${LS_TIMEFMT} "$@" \
| sed -E \
        -e "s/^(d[rwx-]{9})/$BLUE\1$R/" \
        -e "s/^(-..x..x..x)/$RED_BOLD\1$R/" \
        -e "s/^(-..-..x..x)/$RED\1$R/" \
        -e "s/^(-..x..-..x)/$RED_BOLD\1$R/" \
        -e "s/^(-..x..x..-)/$RED_BOLD\1$R/" \
        -e "s/^(-..-..-..x)/$RED\1$R/" \
        -e "s/^(-..x..-..-)/$RED_BOLD\1$R/" \
        -e "s/^(-..-..x..-)/$RED\1$R/" \
        -e "s/^([^ ]+ +[^ ]+ +[^ ]+ +[^ MG]+)([MG]{0,1})( +.+)/\1${GREEN_BOLD}\2$R\3/" \
        -e "s/^([^ ]+ +[^ ]+ +[^ ]+ +)([^ ]+)( +.+)/\1${GREEN}\2$R\3/" \
        -e "s/^([^ ]+ +[^ ]+ +[^ ]+ +[^ ]+ +)(...{0,1} .{6}$(/bin/date '+%y') .{5})( .+)/\1${ITALIC}${GRAY8}\2$R\3/" \
        -e "s/^([^ ]+ +[^ ]+ +[^ ]+ +[^ ]+ +)(...{0,1} .{6}${DATE_LAST_YEAR} .{5})( .+)/\1${ITALIC}${GRAY4}\2$R\3/" \
        -e "s/^([^ ]+ +[^ ]+ +[^ ]+ +[^ ]+ +)(.{11,12} .{5})( .+)/\1${ITALIC}${GRAY1}\2$R\3/" \
        -e "s/ $USER / ${GRAY0}${USER}$R /"
